# Generated by Django 4.2.5 on 2023-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
