# Generated by Django 4.2.5 on 2023-09-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_experiencetechnology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='experiencetechnology',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='folio.experience'),
        ),
    ]
